# Generated by Django 2.0.2 on 2018-03-21 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(max_length=15)),
                ('port_type', models.BooleanField()),
                ('port_state', models.BooleanField()),
                ('is_change', models.BooleanField()),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctrl', models.BooleanField()),
                ('loop', models.BooleanField()),
                ('port_id', models.IntegerField()),
                ('s_time', models.IntegerField()),
                ('c_time', models.IntegerField()),
            ],
        ),
    ]
