# Generated by Django 2.0.2 on 2018-03-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='port_state',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='port',
            name='port_type',
            field=models.IntegerField(),
        ),
    ]
